---
- name: AWS instance creation
  hosts: localhost
  gather_facts: no
  vars:
     account_details: "{{ lookup('aws_account_attribute', wantlist='true') }}"
  tasks:
    - name: Get available VPC ID
      amazon.aws.ec2_vpc_net_info:
        region: "{{ ec2_region }}"
      register: vpc_net_facts

    - name: Get the subnet IDs for {{ ec2_name_prefix }}-vpc
      amazon.aws.ec2_vpc_subnet_info:
        region: "{{ ec2_region }}"
        filters:
          vpc-id: "{{ vpc_net_facts.vpcs[0].id }}"
      register: subnet_info

    - name: "Find current, region-specific AMI."
      amazon.aws.ec2_ami_info:
        region: "{{ ec2_region }}"
        filters:
          name: "{{ ami_name }}"
      register: found_amis

    - name: "Set AMI value"
      set_fact:
        book_ami: "{{ found_amis.images | selectattr('name', 'defined') | sort(attribute='creation_date') | last }}"
      when: found_amis.images is defined

    - name: Setup an instance for testing
      amazon.aws.ec2:
        key_name: ansibleAWS
        instance_type: t2.micro
        image: "{{ book_ami.image_id }}"
        region: "{{ ec2_region }}"
        vpc_subnet_id: "{{ subnet_id }}"
        group_id: "{{ sec_group_id }}"
        wait: yes
        assign_public_ip: yes
        count: 1
        volumes:
          - device_name: /dev/xvdb
            volume_size: 5
            delete_on_termination: true
        instance_tags:
          Role: rhel_server
          Platform: RHEL
      register: ec2
    
    - name: debug
        var: account_details
...
