---
- name: Prepare VPC
  hosts: localhost
  tags:
    - create
  vars:
    state: present
  roles:
    - role: aws_vpc

- name: test
  debug:
    msg: test
    
- name: Destroy VPC
  hosts: localhost
  tags:
    - delete
    - never
  vars:
    state: absent
  roles:
    - role: aws_vpc
...
