---
- name: Prepare VPC
  hosts: control
  tags:
    - create
  vars:
    state: present
  roles:
    - role: aws_vpc

- name: Destroy VPC
  hosts: control
  tags:
    - delete
    - never
  vars:
    state: absent
  roles:
    - role: aws_vpc
...
